# Enable actuator endpoints:
#  - health: used by LivenessProbe and ReadinessProbe to mark this app as running
#  - prometheus: used by Prometheus to scrape app metrics
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
