management:
  endpoints:
    web:
      exposure:
        # Enable actuator endpoints:
        #  - health: used by LivenessProbe and ReadinessProbe to verify if this app is actually running
        #  - prometheus: used by Prometheus to scrape app metrics
        include: health, prometheus
  endpoint:
    health:
      probes:
        # Always enable health probes: whenever you build native images with GraalVM,
        # you need to set this property to true.
        enabled: true
