version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  arm64-native:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
    - run:
        name: Login to ghcr.io
        command: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
    - checkout
    - sdkman/setup-sdkman
    - sdkman/sdkman-install:
        candidate: java
        version: 17.0.9-graalce
    - run:
        name: Build image
        command: ./mvnw -Pnative spring-boot:build-image -DskipTests
    - run:
        name: Publish image to ghcr.io
        command: |
          docker tag ghcr.io/alexandreroman/spring-on-k8s:latest ghcr.io/alexandreroman/spring-on-k8s:linux-arm64
          docker push ghcr.io/alexandreroman/spring-on-k8s:linux-arm64

workflows:
  arm64-native-workflow:
    jobs:
    - arm64-native:
        context:
        - ghcr
